DROP TABLE IF EXISTS `Hotel`;
DROP TABLE IF EXISTS `Room`;
DROP TABLE IF EXISTS `Account`;
DROP TABLE IF EXISTS `Order`;

CREATE TABLE `Hotel`(
	id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
	star Int NOT NULL,
	locality VARCHAR(100) NOT NULL,
	street_address VARCHAR(100) NOT NULL,
	owner_id INTEGER
);


CREATE TABLE `Room`(
	id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
	type VARCHAR(100) NOT NULL,
	price Int Not NULL,
	quantity Int Not NULL,
	hotel_id Int Not NULL
);

CREATE TABLE `Account`(
	id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL
);

CREATE TABLE `Order`(
	id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
	account_id INTEGER NOT NULL,
	room_id INTEGER NOT NULL,
	quantity Int Not NULL,
	dateIn Datetime NOT NULL,
	dateOut Datetime NOT NULL,
	owner_id INTEGER
);
